name: Checkout Example

on: push

jobs:
  build:
    runs-on: ubuntu-22.04

    
    steps:
      - name: Check Installed Tools
        run: |
          git --version
          node --version
          python --version
          docker --version
