name: Checkout Example

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: List Files
        run: ls -la
    
      - name: Bash Script
        run: |
          echo "Starting Build"

          for i in 1 2 3
          do
            echo "Step $i"
          done

    steps:
      - name: Install Tree Package
        run: |
          sudo apt-get update
          sudo apt-get install tree -y

      - name: Verify Installation
        run: tree
